import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/Navbar'
import { Providers } from './../providers';
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <Navbar />
          <Providers>
            {children}
          </Providers>
          </body>
        </html>
      </ClerkProvider>
  )
}

export const metadata = {
  title: "Nextjs Notes App",
  description: 'Generated by create next app',
}